[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/content.json"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/admin.html"
  [headers.values]
    Cache-Control = "no-store"
    X-Robots-Tag = "noindex, nofollow"
